name: Deco
version: 1.0.0
main: net.airone01.deco.Deco
description: Decoration for your server
author: AirOne01
website: https://papermc.io
api-version: '1.20'
commands:
  deco:
    description: Main command
    usage: /<command> [reload]
    tab-completer: net.airone01.deco.commands.DecoTabCompleter
    executor: net.airone01.deco.commands.DecoCommand